/*
** input_buttons.h
**
** This file is part of HiddenChest.
**
** Copyright (C) 2018-2026 Kyonides Arkanthes <kyonides@gmail.com>
*/

struct
{
  const char *str;
  Input::ButtonCode val;
}
static buttonCodes[] =
{
  { "DOWN",           Input::Down  },
  { "LEFT",           Input::Left  },
  { "RIGHT",          Input::Right },
  { "UP",             Input::Up    },
  { "Down",           Input::Down  },
  { "Left",           Input::Left  },
  { "Right",          Input::Right },
  { "Up",             Input::Up    },
  { "A",              Input::A     },
  { "B",              Input::B     },
  { "C",              Input::C     },
  { "X",              Input::X     },
  { "Y",              Input::Y     },
  { "Z",              Input::Z     },
  { "L",              Input::L     },
  { "R",              Input::R     },
  { "L2",             Input::L2    },
  { "R2",             Input::R2    },
  { "SHIFT",          Input::Shift },
  { "CTRL",           Input::Ctrl  },
  { "ALT",            Input::Alt   },
  { "Shift",          Input::Shift },
  { "Ctrl",           Input::Ctrl  },
  { "Alt",            Input::Alt   },
  { "KeyA",           Input::KeyA  },
  { "KeyB",           Input::KeyB  },
  { "KeyC",           Input::KeyC  },
  { "KeyD",           Input::KeyD  },
  { "KeyE",           Input::KeyE  },
  { "KeyF",           Input::KeyF  },
  { "KeyG",           Input::KeyG  },
  { "KeyH",           Input::KeyH  },
  { "KeyI",           Input::KeyI  },
  { "KeyJ",           Input::KeyJ  },
  { "KeyK",           Input::KeyK  },
  { "KeyL",           Input::KeyL  },
  { "KeyM",           Input::KeyM  },
  { "KeyN",           Input::KeyN  },
  { "KeyO",           Input::KeyO  },
  { "KeyP",           Input::KeyP  },
  { "KeyQ",           Input::KeyQ  },
  { "KeyR",           Input::KeyR  },
  { "KeyS",           Input::KeyS  },
  { "KeyT",           Input::KeyT  },
  { "KeyU",           Input::KeyU  },
  { "KeyV",           Input::KeyV  },
  { "KeyW",           Input::KeyW  },
  { "KeyX",           Input::KeyX  },
  { "KeyY",           Input::KeyY  },
  { "KeyZ",           Input::KeyZ  },
  { "N1",             Input::N1    },
  { "N2",             Input::N2    },
  { "N3",             Input::N3    },
  { "N4",             Input::N4    },
  { "N5",             Input::N5    },
  { "N6",             Input::N6    },
  { "N7",             Input::N7    },
  { "N8",             Input::N8    },
  { "N9",             Input::N9    },
  { "N0",             Input::N0    },
  { "Return",         Input::Return         },
  { "Escape",         Input::Escape         },
  { "Backspace",      Input::Backspace      },
  { "Space",          Input::Space          },
  { "Minus",          Input::Minus          },
  { "Equals",         Input::Equals         },
  { "LeftBracket",    Input::LeftBracket    },
  { "RightBracket",   Input::RightBracket   },
  { "Leftbracket",    Input::LeftBracket    },
  { "Rightbracket",   Input::RightBracket   },
  { "BackSlash",      Input::BackSlash      },
  { "Semicolon",      Input::Semicolon      },
  { "Apostrophe",     Input::Apostrophe     },
  { "Grave",          Input::Grave          },
  { "Comma",          Input::Comma          },
  { "Period",         Input::Period         },
  { "Slash",          Input::Slash          },
  { "Tab",            Input::Tab            },
  { "F1",             Input::F1             },
  { "F2",             Input::F2             },
  { "F3",             Input::F3             },
  { "F4",             Input::F4             },
  { "F5",             Input::F5             },
  { "F6",             Input::F6             },
  { "F7",             Input::F7             },
  { "F8",             Input::F8             },
  { "F9",             Input::F9             },
  { "F10",            Input::F10            },
  { "F11",            Input::F11            },
  { "F12",            Input::F12            },
  { "PrintScreen",    Input::PrintScreen    },
  { "ScrollLock",     Input::ScrollLock     },
  { "CapsLock",       Input::CapsLock       },
  { "Printscreen",    Input::PrintScreen    },
  { "Scrolllock",     Input::ScrollLock     },
  { "Capslock",       Input::CapsLock       },
  { "Pause",          Input::Pause          },
  { "Insert",         Input::Insert         },
  { "Home",           Input::Home           },
  { "PageUp",         Input::PageUp         },
  { "Pageup",         Input::PageUp         },
  { "Delete",         Input::Delete         },
  { "End",            Input::End            },
  { "PageDown",       Input::PageDown       },
  { "Pagedown",       Input::PageDown       },
  { "NumPadDivide",   Input::NumPadDivide   },
  { "NumPadMultiply", Input::NumPadMultiply },
  { "NumPadMinus",    Input::NumPadMinus    },
  { "NumPadPlus",     Input::NumPadPlus     },
  { "Enter",          Input::Enter          },
  { "NumPad1",        Input::NumPad1        },
  { "NumPad2",        Input::NumPad2        },
  { "NumPad3",        Input::NumPad3        },
  { "NumPad4",        Input::NumPad4        },
  { "NumPad5",        Input::NumPad5        },
  { "NumPad6",        Input::NumPad6        },
  { "NumPad7",        Input::NumPad7        },
  { "NumPad8",        Input::NumPad8        },
  { "NumPad9",        Input::NumPad9        },
  { "NumPad0",        Input::NumPad0        },
  { "NumPadDot",      Input::NumPadDot      },
  { "LessOrGreater",  Input::LessOrGreater  },
  { "Lessorgreater",  Input::LessOrGreater  },
  { "APP",            Input::APP            },
  { "NumPadEquals",   Input::NumPadEquals   },
  { "LeftCtrl",       Input::LeftCtrl       },
  { "LeftShift",      Input::LeftShift      },
  { "LeftAlt",        Input::LeftAlt        },
  { "LeftMeta",       Input::LeftMeta       },
  { "Leftctrl",       Input::LeftCtrl       },
  { "Leftshift",      Input::LeftShift      },
  { "Leftalt",        Input::LeftAlt        },
  { "Leftmeta",       Input::LeftMeta       },
  { "RightCtrl",      Input::RightCtrl      },
  { "RightShift",     Input::RightShift     },
  { "RightAlt",       Input::RightAlt       },
  { "RightMeta",      Input::RightMeta      },
  { "Rightctrl",      Input::RightCtrl      },
  { "Rightshift",     Input::RightShift     },
  { "Rightalt",       Input::RightAlt       },
  { "Rightmeta",      Input::RightMeta      },
  { "Web",            Input::Web            },
  { "Mail",           Input::Mail           },
  { "Calculator",     Input::Calculator     },
  { "Computer",       Input::Computer       },
  { "APP1",           Input::APP1           },
  { "APP2",           Input::APP2           },
  { "MOUSELEFT",      Input::MouseLeft      },
  { "MOUSEMIDDLE",    Input::MouseMiddle    },
  { "MOUSERIGHT",     Input::MouseRight     },
  { "MouseLeft",      Input::MouseLeft      },
  { "MouseMiddle",    Input::MouseMiddle    },
  { "MouseRight",     Input::MouseRight     }
};

static elementsN(buttonCodes);

struct
{
  Input::ButtonCode code;
  const char *str;
}
static buttonStrings[] =
{
  { Input::Left,           0  },
  { Input::Right,          0  },
  { Input::N1,           "1"  },
  { Input::N2,           "2"  },
  { Input::N3,           "3"  },
  { Input::N4,           "4"  },
  { Input::N5,           "5"  },
  { Input::N6,           "6"  },
  { Input::N7,           "7"  },
  { Input::N8,           "8"  },
  { Input::N9,           "9"  },
  { Input::N0,           "0"  },
  { Input::KeyA,         "A"  },
  { Input::KeyB,         "B"  },
  { Input::KeyC,         "C"  },
  { Input::KeyD,         "D"  },
  { Input::KeyE,         "E"  },
  { Input::KeyF,         "F"  },
  { Input::KeyG,         "G"  },
  { Input::KeyH,         "H"  },
  { Input::KeyI,         "I"  },
  { Input::KeyJ,         "J"  },
  { Input::KeyK,         "K"  },
  { Input::KeyL,         "L"  },
  { Input::KeyM,         "M"  },
  { Input::KeyN,         "N"  },
  { Input::KeyO,         "O"  },
  { Input::KeyP,         "P"  },
  { Input::KeyQ,         "Q"  },
  { Input::KeyR,         "R"  },
  { Input::KeyS,         "S"  },
  { Input::KeyT,         "T"  },
  { Input::KeyU,         "U"  },
  { Input::KeyV,         "V"  },
  { Input::KeyW,         "W"  },
  { Input::KeyX,         "X"  },
  { Input::KeyY,         "Y"  },
  { Input::KeyZ,         "Z"  },
  { Input::Space,        " "  },
  { Input::Minus,        "-"  },
  { Input::Comma,        ","  },
  { Input::Semicolon,    ";"  },
  { Input::Apostrophe,   "'"  },
  { Input::Period,       "."  },
  { Input::NumPadDot,    "."  },
  { Input::NumPadEquals, "="  },
  { Input::NumPad1,      "1"  },
  { Input::NumPad2,      "2"  },
  { Input::NumPad3,      "3"  },
  { Input::NumPad4,      "4"  },
  { Input::NumPad5,      "5"  },
  { Input::NumPad6,      "6"  },
  { Input::NumPad7,      "7"  },
  { Input::NumPad8,      "8"  },
  { Input::NumPad9,      "9"  },
  { Input::NumPad0,      "0"  },
  { Input::LeftBracket,  "["  },
  { Input::RightBracket, "]"  },
  { Input::Slash,        "/"  },
  { Input::BackSlash,    "\\" }
};

static elementsN(buttonStrings);