#define HIDDENAUTHOR "Kyonides Arkanthes"
#define HIDDENVERSION "1.1.75"
#define HIDDENDATE "2024-06-02"
#define CODENAME "SplashScreen"
#define SYSTEM_STRING "linux"
#define SYSTEM_REAL_STRING "Linux"
