#define HIDDENAUTHOR "Kyonides Arkanthes"
#define HIDDENVERSION "1.1.70"
#define HIDDENDATE "2024-05-24"
#define CODENAME "Click-a-Mole"
#define SYSTEM_STRING "linux"
#define SYSTEM_REAL_STRING "Linux"
