#define HIDDENAUTHOR "Kyonides Arkanthes"
#define HIDDENVERSION "1.1.83"
#define HIDDENDATE "2024-09-29"
#define CODENAME "HeadPhones"
#define SYSTEM_STRING "linux"
#define SYSTEM_REAL_STRING "Linux"
